config/routes.rb
ShenyunCrm::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => "events#index"
 
  get "events/index"
  resources :events

  get "me/events"
  get "me/join"

  resources :events do
    member do
      post :join
      post :quit
    end
  end

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :owner, :class_name => "User", :foreign_key => :user_id
  has_many :event_users
  has_many :event_quit_users
  has_many :members, :through => :event_users, :source => :user
  has_many :quit_members, :through => :event_quit_users, :source => :user
  
  validates :title, :presence => true

  after_create :join_owner_to_event

  def join_owner_to_event
    members << owner
  end

  def quit_member_from_event
    quit_members << owner
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  layout "crm"
  before_action :login_required
  
  def new

    @event = Event.new

  end

  def index

    @events = Event.all

  end

  def show
    @event = Event.find(params[:id])
    @users = @event.members
    @quit_users = @event.quit_members

  end

  def join

  @event = Event.find(params[:id])
  
  if !current_user.is_member_of?(@event)
    if is_full_member?(@event)  
      flash[:warning] = "此活動報名人數已滿"
    else
      if is_out_of_date?(@event)
        flash[:warning] = "已超過報名截止時間"
      else
        UserMailer.confirm(current_user.email, { :user_name => current_user.name, :event_title => @event.title}).deliver
        current_user.join!(@event)
      end
    end
  else     
     flash[:warning] = "你已經加入此活動"
  end
  
  redirect_to "/events/index"
 
 end

 def is_full_member?(event)
  return (event.members.count >= event.person_limit.to_i)
 end

 def is_out_of_date?(event)
  out_date = event.active_date.split('~')[1]
  return Date.parse(out_date) < Date.today
 end

 def quit
   @event = Event.find(params[:id])

   if current_user.is_member_of?(@event)
     current_user.quit!(@event)
     @event.quit_member_from_event
   else
     flash[:warning] = "你並不是此活動的會員"
   end

   redirect_to "/events/index"
 end




  def create

    @event = Event.new(event_params)
    @event.user_id = current_user.id

    @event.save

    flash[:warning] = "新增成功"

    redirect_to "/events/new"
  end

  def event_params
    params.require(:event).permit(:title, :content, :person_limit, :active_date, :location, :price)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="setting_panel"> 
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">自己的活動列表</h3>
    </div>
    <div class="panel-body">
      <span class="label label-info">總活動數 <%= @events.count %>人</span>
      <div class="panel panel-default">
        <table class="table list_table">
          <thead>
            <th>標題</th>
            <th>內容</th>
            <th>報名人數上限</th>
            <th>報名開始日語報名截止日</th>
            <th>地點</th>
            <th>價格</th>
            <th>加入</th>
            <th>退出</th>
          </thead>
          <% @events.each do |event| %>
          <tr>
            <td>
              <%= event.title %>    
            </td>
            <td>
              <%= event.content %>
            </td>
            <td>  
              <%= event.person_limit %>
            </td>
            <td>
              <%= event.active_date %>
            </td>
            <td>                 
              <%= event.location %>      
            </td>
            <td>
              <%= event.price %>
            </td>
            <td>
              <% if !current_user.is_member_of?(event) %>
                <%= link_to("加入", join_event_path(event), :method => :post, :class => "btn btn-mini") %>
              <% end %> 
            </td>
            <td>
              <% if current_user.is_member_of?(event) %>
                <%= link_to("退出", quit_event_path(event), :method => :post, :class => "btn btn-mini") %>
              <% end %> 
            </td>
          </tr>
          <% end %>
        </table>
      </div>     
    </div>
  </div>
</div>  

app/views/events/new.html.erb
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.4.1/bootstrap-select.min.css">
<script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.4.1/bootstrap-select.min.js"></script>
<script type="text/javascript">
    $(window).on('load', function () {

        $('.selectpicker').selectpicker({
            'selectedText': 'cat'
        });

        // $('.selectpicker').selectpicker('hide');
    });
</script>
<div class="setting_panel">
  <%= form_for @event do |f| %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">開辦活動</h3>
    </div>
    <div class="panel-body">
        <div class="input-group">
          <%= f.label :title, "標題",:class => "input-group-addon" %>
          <%= f.text_field :title, :class => "form-control", :placeholder => "標題" %>
        </div>
        <div class="input-group">
          <%= f.label :content, "內容",:class => "input-group-addon" %>
          <%= f.text_field :content, :class => "form-control", :placeholder => "內容" %>
        </div>
        <div class="input-group">
          <%= f.label :person_limit, "報名人數上限",:class => "input-group-addon" %>
          <%= f.text_field :person_limit, :class => "form-control", :placeholder => "報名人數上限" %>
        </div>
        <div class="input-group">
          <%= f.label :active_date, "報名開始日與報名截止日",:class => "input-group-addon" %>
          <%= f.text_field :active_date, :class => "form-control", :placeholder => "報名開始日與報名截止日" %>
        </div>
        <div class="input-group">
          <%= f.label :location, "地點",:class => "input-group-addon" %>
          <%= f.text_field :location, :class => "form-control", :placeholder => "地點" %>
        </div>
          <div class="input-group">
          <%= f.label :price, "價格",:class => "input-group-addon" %>
          <%= f.text_field :price, :class => "form-control", :placeholder => "價格" %>
        </div>

        <div class="input-group input-group-center">
          <%= f.submit("新增", :class => "btn btn-default" ) %>
        </div>
    </div>
  </div>
  
<% end %>
</div>

app/views/events/show.html.erb
<div class="setting_panel"> 
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">此活動報名會員</h3>
    </div>
    <div class="panel-body">
      <span class="label label-info">會員數 <%= @users.count %>人</span>
      <div class="panel panel-default">
        <table class="table list_table">
          <thead>
            <th>姓名</th>
            <th>email</th>
          </thead>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= user.name %>    
            </td>
            <td>
              <%= user.email %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>     
    </div>
  </div>
</div>  

<div class="setting_panel"> 
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">此活動退出會員</h3>
    </div>
    <div class="panel-body">
      <span class="label label-info"></span>
      <div class="panel panel-default">
        <table class="table list_table">
          <thead>
            <th>姓名</th>
            <th>email</th>
          </thead>
          <% @quit_users.each do |user| %>
          <tr>
            <td>
              <%= user.name %>    
            </td>
            <td>
              <%= user.email %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>     
    </div>
  </div>
</div>  